# Generated by Django 4.1.2 on 2022-10-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Programador'), ('4', 'Ingeniero'), ('5', 'Abogado'), ('6', 'Licenciado')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
