# Generated by Django 4.1.2 on 2022-10-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_empleado_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='hoja_vida',
        ),
    ]
