# Generated by Django 4.1.2 on 2022-10-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_empleado_full_name_alter_empleado_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.CharField(choices=[('0', 'Activo'), ('1', 'Borrado')], default='0', max_length=1, verbose_name='Activo'),
        ),
    ]
