# Generated by Django 4.1.2 on 2022-10-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybase',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mybase',
            name='subtitulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mybase',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
